version: '3.7'

services:
  web:
    build: ./spotify
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./spotify:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build: ./spotify
    command: celery worker --app=spotify_project.celery_app --loglevel=info
    volumes:
      - ./spotify:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=artur
      - POSTGRES_PASSWORD=artur
      - POSTGRES_DB=spotify_app_dev

volumes:
  postgres_data:
