# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=32, unique=True)),
                ('track_artist', models.CharField(max_length=128)),
                ('track_name', models.CharField(max_length=128)),
                ('danceability', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('valence', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('energy', models.FloatField()),
                ('liveness', models.FloatField()),
            ],
        ),
    ]
