# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=32, unique=True)),
                ('album_artist', models.CharField(max_length=128)),
                ('album_name', models.CharField(max_length=128)),
                ('danceability', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('valence', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('energy', models.FloatField()),
                ('liveness', models.FloatField()),
            ],
        ),
    ]
