# Generated by Django 2.2 on 2019-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_auto_20190424_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.URLField(null=True),
        ),
    ]
